ftrace: ftrace::FpImplementation Class Reference
ftrace::FpImplementation Class Reference abstract
#include <fp_implementation.h>
Public Member Functions
virtual FLT32 PerformOperation (const FpOperation &operation)
Protected Member Functions
virtual FLT32 FpAdd (const FpOperation &operation)=0
virtual FLT32 FpSub (const FpOperation &operation)=0
virtual FLT32 FpMul (const FpOperation &operation)=0
virtual FLT32 FpDiv (const FpOperation &operation)=0
Detailed Description
Implementation of floating-point arithmetic to be used in the ftrace instrumentation tool.
Definition at line 14 of file fp_implementation.h.
Member Function Documentation
FpAdd()
virtual FLT32 ftrace::FpImplementation::FpAdd (const FpOperation & operation) protected pure virtual
Performs floating-point addition.
Parameters
[in] operation The operation to perform.
Returns
The result of the floating-point addition.
Implemented in ftrace::NormalFpImplementation, and ftrace::TestSimpleFpImplementation.
Referenced by PerformOperation().
FpDiv()
virtual FLT32 ftrace::FpImplementation::FpDiv (const FpOperation & operation) protected pure virtual
Performs floating-point division.
Parameters
[in] operation The operation to perform.
Returns
The result of the floating-point division.
Implemented in ftrace::NormalFpImplementation, and ftrace::TestSimpleFpImplementation.
Referenced by PerformOperation().
FpMul()
virtual FLT32 ftrace::FpImplementation::FpMul (const FpOperation & operation) protected pure virtual
Performs floating-point multiplication.
Parameters
[in] operation The operation to perform.
Returns
The result of the floating-point multiplication.
Implemented in ftrace::NormalFpImplementation, and ftrace::TestSimpleFpImplementation.
Referenced by PerformOperation().
FpSub()
virtual FLT32 ftrace::FpImplementation::FpSub (const FpOperation & operation) protected pure virtual
Performs floating-point subtraction.
Parameters
[in] operation The operation to perform.
Returns
The result of the floating-point subtraction.
Implemented in ftrace::NormalFpImplementation, and ftrace::TestSimpleFpImplementation.
Referenced by PerformOperation().
PerformOperation()
FLT32 ftrace::FpImplementation::PerformOperation (const FpOperation & operation) virtual
Performs a single floating-point arithmetic operation.
Parameters
[in] operation The operation to perform.
Returns
The result of the floating-point operation.
Reimplemented in ftrace::TestComplexFpImplementation.
Definition at line 12 of file fp_implementation.cpp.
References FpAdd(), FpDiv(), FpMul(), and FpSub().
Referenced by ftrace::TestComplexFpImplementation::PerformOperation(), ftrace::analysis::anonymous_namespace{replace_fp_operations.cpp}::ReplaceMemoryFpInstruction(), and ftrace::analysis::anonymous_namespace{replace_fp_operations.cpp}::ReplaceRegisterFpInstruction().
The documentation for this class was generated from the following files:
src/client_lib/interfaces/fp_implementation.h
src/client_lib/interfaces/fp_implementation.cpp