ftrace: ftrace::FpSelector Class Reference
ftrace::FpSelector Class Reference abstract
#include <fp_selector.h>
Public Member Functions
virtual VOID StartCallback ()
virtual VOID ExitCallback (const INT32 &code)
virtual VOID OnFunctionStart (const string &function_name)
virtual VOID OnFunctionEnd (const string &function_name)
virtual FpImplementation * SelectFpImplementation (const FpOperation &operation)=0
Detailed Description
Selects which floating-point arithmetic implementation to use for an arithmetic operation depending on the current state of the instrumented application.
Definition at line 18 of file fp_selector.h.
Member Function Documentation
ExitCallback()
virtual VOID ftrace::FpSelector::ExitCallback (const INT32 & code) inline virtual
Called after the instrumented application finishes running to perform teardown for this class.
Parameters
[in] code OS specific termination code for the application.
Definition at line 32 of file fp_selector.h.
Referenced by ftrace::callbacks::anonymous_namespace{replace_fp_operations.cpp}::ExitCallback().
OnFunctionEnd()
virtual VOID ftrace::FpSelector::OnFunctionEnd (const string & function_name) inline virtual
Called whenever a function ends in the instrumented application to perform per-function setup for this class.
Parameters
[in] function_name The name of the function that is ending.
Reimplemented in ftrace::internal::FunctionStackFpSelector.
Definition at line 48 of file fp_selector.h.
References SelectFpImplementation().
Referenced by ftrace::analysis::anonymous_namespace{replace_fp_operations.cpp}::ExitFunction().
OnFunctionStart()
virtual VOID ftrace::FpSelector::OnFunctionStart (const string & function_name) inline virtual
Called whenever a function begins in the instrumented application to perform per-function setup for this class.
Parameters
[in] function_name The name of the function that is beginning.
Reimplemented in ftrace::internal::FunctionStackFpSelector.
Definition at line 40 of file fp_selector.h.
Referenced by ftrace::analysis::anonymous_namespace{replace_fp_operations.cpp}::EnterFunction().
SelectFpImplementation()
virtual FpImplementation* ftrace::FpSelector::SelectFpImplementation (const FpOperation & operation) pure virtual
Selects a floating-point arithmetic implementation to use for the supplied floating-point instruction.
Parameters
[in] operation The floating-point instruction to be performed.
Returns
The floating-point implementation to use to calculate the result of the arithmetic instruction.
Implemented in ftrace::internal::FunctionStackFpSelector, ftrace::internal::CurrentFunctionFpSelector, and ftrace::internal::SingleFpImplementationSelector< FpImpl >.
Referenced by OnFunctionEnd(), ftrace::analysis::anonymous_namespace{replace_fp_operations.cpp}::ReplaceMemoryFpInstruction(), and ftrace::analysis::anonymous_namespace{replace_fp_operations.cpp}::ReplaceRegisterFpInstruction().
StartCallback()
virtual VOID ftrace::FpSelector::StartCallback () inline virtual
Called before the instrumented application runs to perform setup for this class.
Definition at line 24 of file fp_selector.h.
Referenced by ftrace::callbacks::anonymous_namespace{replace_fp_operations.cpp}::StartCallback().
The documentation for this class was generated from the following file:
src/client_lib/interfaces/fp_selector.h