ftrace: ftrace::internal::FpSelectorRegistry Class Reference
ftrace::internal::FpSelectorRegistry Class Reference
#include <fp_selector_registry.h>
Public Member Functions
VOID RegisterFpSelector (FpSelector *fp_selector, const string &fp_selector_name)
FpSelector * GetFpSelectorOrDie (const string &fp_selector_name) const
Static Public Member Functions
static FpSelectorRegistry * GetFpSelectorRegistry ()
Private Attributes
unordered_map< string, FpSelector * > fp_selector_map_
Mapping from names to FpSelector instances.
Detailed Description
Contains a mapping from names to FpSelector instances. This is used to determine which FpSelector instance to use to instrument a program when the KnobFpSelectorName flag is supplied on the command line.
Definition at line 19 of file fp_selector_registry.h.
Member Function Documentation
GetFpSelectorOrDie()
FpSelector * ftrace::internal::FpSelectorRegistry::GetFpSelectorOrDie (const string & fp_selector_name) const
Returns the FpSelector instance mapped to the supplied name, or exits the application if no instance is mapped to that name.
Parameters
[in] fp_selector_name The name to look up in the registry.
Returns
The FpSelector instance mapped to the supplied name.
Definition at line 31 of file fp_selector_registry.cpp.
References fp_selector_map_.
GetFpSelectorRegistry()
FpSelectorRegistry * ftrace::internal::FpSelectorRegistry::GetFpSelectorRegistry () static
Returns the global registry for FpSelector instances.
Definition at line 18 of file fp_selector_registry.cpp.
Referenced by ftrace::RegisterFpSelector< internal::SingleFpImplementationSelector< FpImpl > >::RegisterFpSelector(), and ftrace::RegisterInitializedFpSelector::RegisterInitializedFpSelector().
RegisterFpSelector()
VOID ftrace::internal::FpSelectorRegistry::RegisterFpSelector (FpSelector * fp_selector, const string & fp_selector_name)
Creates a new mapping from a name to an FpSelector instance in the registry.
Parameters
[in] fp_selector The FpSelector instance to register.
[in] fp_selector_name The name to register for the FpSelector instance.
Definition at line 22 of file fp_selector_registry.cpp.
References fp_selector_map_.
Referenced by ftrace::RegisterFpSelector< internal::SingleFpImplementationSelector< FpImpl > >::RegisterFpSelector(), and ftrace::RegisterInitializedFpSelector::RegisterInitializedFpSelector().
The documentation for this class was generated from the following files:
src/client_lib/registry/internal/fp_selector_registry.h
src/client_lib/registry/internal/fp_selector_registry.cpp