import argparse
import sys

def read_replacement_type_mapping(input_file_name):
    replacement_type_mapping = {}

    try:
        input_file = open(input_file_name, 'r')
    except FileNotFoundError:
        print('Input file %s not found' % input_file_name)
        raise
    except IOError:
        print('Cannot open %s\n' % input_file_name)
        raise

    for line in input_file:
        replacement_type, functions_str = line.split(maxsplit=1)
        functions_list = [func_name.strip()
                          for func_name
                          in functions_str.split(',')]

        replacement_type_mapping[replacement_type] = functions_list

    return replacement_type_mapping

def main():
    parser = argparse.ArgumentParser(
        description='''Generate an enum for each replacement type and a
                       corresponding replacement type to instrumented function
                       name mapping''')

    parser.add_argument('-o', '--output',
                        help='File to store generated code, defaults to stdout')
    parser.add_argument('-i', '--input',
                        help='''File containing a mapping from instrumented
                                functions to replacement types, to be used as
                                input''')

    args = parser.parse_args()

    if args.input:
        replacement_type_mapping = read_replacement_type_mapping(args.input)
    else:
        replacement_type_mapping = {}

    if args.output:
        output_file = open(args.output, 'w')
    else:
        output_file = sys.stdout

    output_file.write('// Generated by generate_replacement_type_enum.py\n')
    output_file.write('\n')
    output_file.write('#include <string>')
    output_file.write('\n')
    output_file.write('using namespace std;\n')
    output_file.write('\n')

    output_file.write('typedef enum replacement_type {\n')
    output_file.write('    default_replacement,\n')
    for replacement_type in replacement_type_mapping.keys():
        output_file.write('    %s,\n' % replacement_type)
    output_file.write('} replacement_type;\n')
    output_file.write('\n')

    output_file.write('struct func_mapping_entry {\n')
    output_file.write('    const char *func_name;\n')
    output_file.write('    replacement_type type;\n')
    output_file.write('};\n')
    output_file.write('\n')

    output_file.write('static struct func_mapping_entry func_mapping_table[]'
                      ' = {\n')
    for mapping_entry in replacement_type_mapping.items():
        replacement_type = mapping_entry[0]

        for func_name in mapping_entry[1]:
            output_file.write('    {"%s", %s},\n'
                              % (func_name, replacement_type))
    output_file.write('    {NULL, default_replacement}\n')
    output_file.write('};\n')
    output_file.write('\n')

    output_file.write('replacement_type get_replacement_type(string func_name)'
                      ' {\n')
    output_file.write('    for (int i=0;'
                      ' func_mapping_table[i].func_name != NULL; i++) {\n')
    output_file.write('        '
                      'if (!func_name.compare(func_mapping_table[i].func_name))'
                      ' {\n')
    output_file.write('            return func_mapping_table[i].type;\n')
    output_file.write('        }\n')
    output_file.write('    }\n')
    output_file.write('\n')
    output_file.write('    return default_replacement;\n')
    output_file.write('}\n')

    output_file.close()


if __name__ == '__main__':
    main()
