NEAT: NEAT Namespace Reference
NEAT Namespace Reference
Namespaces
Classes
class FpImplementation
struct FpOperation
class FpSelector
class NormalFpImplementation
class RegisterCurrentFunctionFpSelector
struct RegisterFpSelector
class RegisterFunctionStackFpSelector
struct RegisterInitializedFpSelector
class RegisterSingleFpImplementationSelector
class TestComplexFpImplementation
class TestSimpleFpImplementation
Functions
VOID PrintFpBitsManipulated (ofstream *output)
VOID PrintFpOperations (ofstream *output)
VOID PrintFunctionNumFpOps (ofstream *output)
VOID ReplaceFpOperations (FpSelector *fp_selector)
BOOL IsFpInstruction (const INS &ins)
static RegisterFunctionStackFpSelector test_simple_function_stack (test_simple_function_stack_map, test_simple_function_stack_map_size, &normal, "test_simple_function_stack")
static RegisterFunctionStackFpSelector test_nested_function_stack (test_nested_function_stack_map, test_nested_function_stack_map_size, &normal, "test_nested_function_stack")
static RegisterCurrentFunctionFpSelector test_simple_current_function (test_simple_function_stack_map, test_simple_function_stack_map_size, &normal, "test_simple_current_function")
static RegisterCurrentFunctionFpSelector test_nested_current_function (test_nested_function_stack_map, test_nested_function_stack_map_size, &normal, "test_nested_current_function")
Variables
static RegisterSingleFpImplementationSelector< NormalFpImplementation > fp_selector ("default")
static TestSimpleFpImplementation simple
static TestComplexFpImplementation complex
static NormalFpImplementation normal
static const pair< string, FpImplementation * > test_simple_function_stack_map []
static const int test_simple_function_stack_map_size
static const pair< string, FpImplementation * > test_nested_function_stack_map []
static const int test_nested_function_stack_map_size
static RegisterSingleFpImplementationSelector< TestSimpleFpImplementation > test_simple ("test_simple")
static RegisterSingleFpImplementationSelector< TestComplexFpImplementation > test_complex ("test_complex")
Detailed Description
Contains utilities used by multiple instrumentation routines.
Function Documentation
IsFpInstruction()
BOOL NEAT::IsFpInstruction (const INS & ins)
Return true if an instruction is an SSE floating-point arithmetic instruction. This function is called on every instruction while the instrumented program is running if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] ins The instruction to test.
Returns
Whether an instruction is a floating-point arithmetic instruction.
Note
Currently, the instructions defined as SSE floating-point arithmetic operations are:
ADDSS
SUBSS
MULSS
DIVSS
Definition at line 7 of file utils.cpp.
Referenced by NEAT::callbacks::anonymous_namespace{print_function_num_fp_ops.cpp}::InstrumentationCallback(), NEAT::callbacks::anonymous_namespace{print_fp_bits_manipulated.cpp}::InstrumentationCallback(), NEAT::callbacks::anonymous_namespace{replace_fp_operations.cpp}::InstrumentationCallback(), and NEAT::callbacks::anonymous_namespace{print_fp_operations.cpp}::InstrumentationCallback().
PrintFpBitsManipulated()
VOID NEAT::PrintFpBitsManipulated (ofstream * output)
Instruments an application with functions to print the number of bits manipulated in every floating-point arithmetic operation in the application.
Parameters
[in] output The output file to write to.
Definition at line 175 of file print_fp_bits_manipulated.cpp.
PrintFpOperations()
VOID NEAT::PrintFpOperations (ofstream * output)
Instruments an application with functions to print the operands and result of every floating-point instruction in the instrumented application.
Parameters
[in] output The output file to write to.
Definition at line 191 of file print_fp_operations.cpp.
PrintFunctionNumFpOps()
VOID NEAT::PrintFunctionNumFpOps (ofstream * output)
Instruments an application with functions to print the number of floating-point arithmetic operations executed per function in the application.
Parameters
[in] output The output file to write to.
Definition at line 102 of file print_function_num_fp_ops.cpp.
ReplaceFpOperations()
VOID NEAT::ReplaceFpOperations (FpSelector * fp_selector)
Instruments an application with functions from the supplied floating-point selector to replace all floating-point arithmetic operations with user-defined implementations.
Parameters
[in,out] fp_selector The floating-point selector.
Definition at line 207 of file replace_fp_operations.cpp.
Variable Documentation
test_nested_function_stack_map
const pair<string, FpImplementation *> NEAT::test_nested_function_stack_map[] static
Initial value:
=
    {{"helper1", &simple}, {"helper2", &simple}, {"nested_helper", &complex}}
Definition at line 51 of file test_fp_selectors.cpp.
test_nested_function_stack_map_size
const int NEAT::test_nested_function_stack_map_size static
Initial value:
=
    sizeof(test_nested_function_stack_map) /
    sizeof(test_nested_function_stack_map[0])
Definition at line 53 of file test_fp_selectors.cpp.
test_simple_function_stack_map
const pair<string, FpImplementation *> NEAT::test_simple_function_stack_map[] static
Initial value:
=
    {{"helper2", &simple}, {"helper1", &complex}}
Definition at line 46 of file test_fp_selectors.cpp.
test_simple_function_stack_map_size
const int NEAT::test_simple_function_stack_map_size static
Initial value:
=
    sizeof(test_simple_function_stack_map) /
    sizeof(test_simple_function_stack_map[0])
Definition at line 48 of file test_fp_selectors.cpp.