NEAT: NEAT::analysis::anonymous_namespace{replace_fp_operations.cpp} Namespace Reference
NEAT::analysis::anonymous_namespace{replace_fp_operations.cpp} Namespace Reference
Functions
VOID ReplaceRegisterFpInstruction (const OPCODE opcode, const REG operand1, const REG operand2, const string *function_name, FpSelector *fp_selector, CONTEXT *ctxt)
VOID ReplaceMemoryFpInstruction (const OPCODE opcode, const REG operand1, const FLT32 *operand2, const string *function_name, FpSelector *fp_selector, CONTEXT *ctxt)
VOID EnterFunction (const string *function_name, FpSelector *fp_selector)
VOID ExitFunction (const string *function_name, FpSelector *fp_selector)
Function Documentation
EnterFunction()
VOID NEAT::analysis::anonymous_namespace{replace_fp_operations.cpp}::EnterFunction (const string * function_name, FpSelector * fp_selector)
Performs any per-function setup needed by the given floating-point selector. This function is called every time a new function is entered in the instrumented application if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] function_name The name of the function being entered.
[in,out] fp_selector The floating-point selector.
Definition at line 84 of file replace_fp_operations.cpp.
References EnterFunction(), and NEAT::FpSelector::OnFunctionStart().
Referenced by EnterFunction().
ExitFunction()
VOID NEAT::analysis::anonymous_namespace{replace_fp_operations.cpp}::ExitFunction (const string * function_name, FpSelector * fp_selector)
Performs any per-function teardown needed by the given floating-point selector. This function is called every time a new function is exited in the instrumented application if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] function_name The name of the function being exited.
[in,out] fp_selector The floating-point selector.
Definition at line 98 of file replace_fp_operations.cpp.
References ExitFunction(), and NEAT::FpSelector::OnFunctionEnd().
Referenced by ExitFunction().
ReplaceMemoryFpInstruction()
VOID NEAT::analysis::anonymous_namespace{replace_fp_operations.cpp}::ReplaceMemoryFpInstruction (const OPCODE opcode, const REG operand1, const FLT32 * operand2, const string * function_name, FpSelector * fp_selector, CONTEXT * ctxt)
Replaces a floating-point operation with a user defined implementation. This function is called for every floating-point arithmetic instruction that operates on a register and a memory location if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] opcode Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction
[in] function_name Name of the function containing this operation.
[in,out] fp_selector Floating-point selector which selects the floating-point implementation to use.
[in,out] ctxt Context of the instrumented application, used to store the result of the floating-point operation in the correct register.
Definition at line 61 of file replace_fp_operations.cpp.
References NEAT::FpImplementation::PerformOperation(), ReplaceMemoryFpInstruction(), and NEAT::FpSelector::SelectFpImplementation().
Referenced by ReplaceMemoryFpInstruction().
ReplaceRegisterFpInstruction()
VOID NEAT::analysis::anonymous_namespace{replace_fp_operations.cpp}::ReplaceRegisterFpInstruction (const OPCODE opcode, const REG operand1, const REG operand2, const string * function_name, FpSelector * fp_selector, CONTEXT * ctxt)
Replaces a floating-point operation with a user defined implementation. This function is called for every floating-point arithmetic instruction that operates on two registers if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] opcode Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction.
[in] function_name Name of the function containing this operation.
[in,out] fp_selector Floating-point selector which selects the floating-point implementation to use.
[in,out] ctxt Context of the instrumented application, used to store the result of the floating-point operation in the correct register.
Definition at line 31 of file replace_fp_operations.cpp.
References NEAT::FpImplementation::PerformOperation(), ReplaceRegisterFpInstruction(), and NEAT::FpSelector::SelectFpImplementation().
Referenced by ReplaceRegisterFpInstruction().