ftrace: ftrace::analysis::anonymous_namespace{print_fp_bits_manipulated.cpp} Namespace Reference
ftrace::analysis::anonymous_namespace{print_fp_bits_manipulated.cpp} Namespace Reference
Functions
VOID CountRegisterFpOperandBits (const PIN_REGISTER *operand1, const PIN_REGISTER *operand2)
VOID CountMemoryFpOperandBits (const PIN_REGISTER *operand1, const FLT32 *operand2)
VOID CountFpResultBits (const PIN_REGISTER *result)
Function Documentation
CountFpResultBits()
VOID ftrace::analysis::anonymous_namespace{print_fp_bits_manipulated.cpp}::CountFpResultBits (const PIN_REGISTER * result)
Counts the number of bits used in the result of a floating-point arithmetic operation. This function is called for every floating-point arithmetic instruction if the KnobPrintFpBitsManipulated flag is supplied on the command line.
Parameters
[in] result Result of the instruction.
Note
The number of bits used is recorded as 23 minus the least significant set bit in the mantissa.
Definition at line 101 of file print_fp_bits_manipulated.cpp.
References CountFpResultBits().
Referenced by CountFpResultBits().
CountMemoryFpOperandBits()
VOID ftrace::analysis::anonymous_namespace{print_fp_bits_manipulated.cpp}::CountMemoryFpOperandBits (const PIN_REGISTER * operand1, const FLT32 * operand2)
Counts the number of bits used in both operands of a floating-point arithmetic operation. This function is called for every floating-point arithmetic instruction that operates on a register and a memory location if the KnobPrintFpBitsManipulated flag is supplied on the command line.
Parameters
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction.
Note
The number of bits used is recorded as 23 minus the least significant set bit in the mantissa.
Definition at line 85 of file print_fp_bits_manipulated.cpp.
References CountMemoryFpOperandBits().
Referenced by CountMemoryFpOperandBits().
CountRegisterFpOperandBits()
VOID ftrace::analysis::anonymous_namespace{print_fp_bits_manipulated.cpp}::CountRegisterFpOperandBits (const PIN_REGISTER * operand1, const PIN_REGISTER * operand2)
Counts the number of bits used in both operands of a floating-point arithmetic operation. This function is called for every floating-point arithmetic instruction that operates on two registers if the KnobPrintFpBitsManipulated flag is supplied on the command line.
Parameters
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction.
Note
The number of bits used is recorded as 23 minus the least significant set bit in the mantissa.
Definition at line 67 of file print_fp_bits_manipulated.cpp.
References CountRegisterFpOperandBits().
Referenced by CountRegisterFpOperandBits().