NEAT: NEAT::callbacks::anonymous_namespace{print_fp_operations.cpp} Namespace Reference
NEAT::callbacks::anonymous_namespace{print_fp_operations.cpp} Namespace Reference
Functions
VOID CloseOutputStream (const INT32 code, ofstream *output)
VOID InstrumentationCallback (const INS ins, ofstream *output)
Function Documentation
CloseOutputStream()
VOID NEAT::callbacks::anonymous_namespace{print_fp_operations.cpp}::CloseOutputStream (const INT32 code, ofstream * output)
Closes the supplied output file. This function is called immediately before the instrumented application exits if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] code Exit code of the pintool.
[in,out] output The output file to close.
Definition at line 133 of file print_fp_operations.cpp.
References CloseOutputStream().
Referenced by CloseOutputStream().
InstrumentationCallback()
VOID NEAT::callbacks::anonymous_namespace{print_fp_operations.cpp}::InstrumentationCallback (const INS ins, ofstream * output)
Schedule calls to analysis routines to print the operands and result of every floating-point instruction in the instrumented application. This function is called every time a new instruction is encountered, before the instrumented application is run if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] ins Instruction to be instrumented.
[in] output The output file to write to.
Definition at line 149 of file print_fp_operations.cpp.
References NEAT::IsFpInstruction().