ftrace: ftrace::callbacks::anonymous_namespace{replace_fp_operations.cpp} Namespace Reference
ftrace::callbacks::anonymous_namespace{replace_fp_operations.cpp} Namespace Reference
Functions
VOID StartCallback (FpSelector *fp_selector)
VOID ExitCallback (const INT32 code, FpSelector *fp_selector)
VOID InstrumentationCallback (const RTN rtn, FpSelector *fp_selector)
Function Documentation
ExitCallback()
VOID ftrace::callbacks::anonymous_namespace{replace_fp_operations.cpp}::ExitCallback (const INT32 code, FpSelector * fp_selector)
Performs any teardown needed by the given floating-point selector. This function is called immediately before the instrumented application exits if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] code Exit code of the pintool.
[in,out] fp_selector The floating-point selector to teardown.
Definition at line 126 of file replace_fp_operations.cpp.
References ftrace::FpSelector::ExitCallback(), and ExitCallback().
Referenced by ExitCallback().
InstrumentationCallback()
VOID ftrace::callbacks::anonymous_namespace{replace_fp_operations.cpp}::InstrumentationCallback (const RTN rtn, FpSelector * fp_selector)
Schedule calls to analysis routines to replace every floating-point operation in the instrumented application with a user-defined implementation. This function is called every time a new routine is encountered, before the instrumented application is run if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] rtn Routine to be instrumented.
[in] fp_selector The floating-point selector to use.
Definition at line 140 of file replace_fp_operations.cpp.
References ftrace::IsFpInstruction().
StartCallback()
VOID ftrace::callbacks::anonymous_namespace{replace_fp_operations.cpp}::StartCallback (FpSelector * fp_selector)
Performs any setup needed by the given floating-point selector. This function is called after Pin initialization is finished but before the instrumented application starts running if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in,out] fp_selector The floating-point selector to setup.
Definition at line 116 of file replace_fp_operations.cpp.
References ftrace::FpSelector::StartCallback(), and StartCallback().
Referenced by StartCallback().