ftrace: ftrace Namespace Reference
ftrace Namespace Reference
Classes
class FpImplementation
class FpSelector
class NormalFpImplementation
struct RegisterFpSelector
class RegisterFunctionLevelFpSelector
struct RegisterInitializedFpSelector
class RegisterSingleFpImplementationSelector
class TestComplexFpImplementation
class TestSimpleFpImplementation
Functions
VOID ReplaceFpOperations (const RTN rtn, FpSelector *fp_selector)
VOID PrintFpOperations (const INS ins, ofstream *output)
VOID StartCallback (FpSelector *fp_selector)
VOID ExitCallback (const INT32 code, FpSelector *fp_selector)
VOID ReplaceRegisterFpInstruction (const OPCODE operation, const REG operand1, const REG operand2, FpSelector *fp_selector, CONTEXT *ctxt)
VOID ReplaceMemoryFpInstruction (const OPCODE operation, const REG operand1, const FLT32 *operand2, FpSelector *fp_selector, CONTEXT *ctxt)
VOID EnterFunction (const string *function_name, FpSelector *fp_selector)
VOID ExitFunction (const string *function_name, FpSelector *fp_selector)
VOID CloseOutputStream (const INT32 code, ofstream *output)
VOID PrintRegisterFpOperands (const OPCODE operation, const PIN_REGISTER *operand1, const PIN_REGISTER *operand2, ofstream *output)
VOID PrintMemoryFpOperands (const OPCODE operation, const PIN_REGISTER *operand1, const FLT32 *operand2, ofstream *output)
VOID PrintFpResult (const PIN_REGISTER *result, ofstream *output)
static RegisterFunctionLevelFpSelector test_simple_function_level (test_simple_function_level_map, test_simple_function_level_map_size, &normal, "test_simple_function_level")
static RegisterFunctionLevelFpSelector test_nested_function_level (test_nested_function_level_map, test_nested_function_level_map_size, &normal, "test_nested_function_level")
Variables
static RegisterSingleFpImplementationSelector< NormalFpImplementation > fp_selector ("default")
static TestSimpleFpImplementation simple
static TestComplexFpImplementation complex
static NormalFpImplementation normal
static const pair< string, FpImplementation * > test_simple_function_level_map []
static const int test_simple_function_level_map_size
static const pair< string, FpImplementation * > test_nested_function_level_map []
static const int test_nested_function_level_map_size
static RegisterSingleFpImplementationSelector< TestSimpleFpImplementation > test_simple ("test_simple")
static RegisterSingleFpImplementationSelector< TestComplexFpImplementation > test_complex ("test_complex")
Detailed Description
Contains callbacks to be used for application instrumentation. All of these functions get called while the instrumented application is running unless otherwise stated.
Function Documentation
CloseOutputStream()
VOID ftrace::CloseOutputStream (const INT32 code, ofstream * output)
Closes the supplied output file. This function is called immediately before the instrumented application exits if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] code Exit code of the pintool.
[in,out] output The output file to close.
Definition at line 63 of file instrumentation_callbacks.cpp.
EnterFunction()
VOID ftrace::EnterFunction (const string * function_name, FpSelector * fp_selector)
Performs any per-function setup needed by the given floating-point selector. This function is called every time a new function is entered in the instrumented application if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] function_name The name of the function being entered.
[in,out] fp_selector The floating-point selector.
Definition at line 55 of file instrumentation_callbacks.cpp.
References ftrace::FpSelector::OnFunctionStart().
Referenced by ReplaceFpOperations().
ExitCallback()
VOID ftrace::ExitCallback (const INT32 code, FpSelector * fp_selector)
Performs any teardown needed by the given floating-point selector. This function is called immediately before the instrumented application exits if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] code Exit code of the pintool.
[in,out] fp_selector The floating-point selector to teardown.
Definition at line 26 of file instrumentation_callbacks.cpp.
References ftrace::FpSelector::ExitCallback().
ExitFunction()
VOID ftrace::ExitFunction (const string * function_name, FpSelector * fp_selector)
Performs any per-function teardown needed by the given floating-point selector. This function is called every time a new function is exited in the instrumented application if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] function_name The name of the function being exited.
[in,out] fp_selector The floating-point selector.
Definition at line 59 of file instrumentation_callbacks.cpp.
References ftrace::FpSelector::OnFunctionEnd().
Referenced by ReplaceFpOperations().
PrintFpOperations()
VOID ftrace::PrintFpOperations (const INS ins, ofstream * output)
Schedule calls to analysis routines to print the operands and result of every floating-point instruction in the instrumented application. This function is called every time a new instruction is encountered, before the instrumented application is run if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] ins Instruction to be instrumented.
[in] output The output file to write to.
Definition at line 102 of file instrument_routine.cpp.
References PrintFpResult(), PrintMemoryFpOperands(), and PrintRegisterFpOperands().
PrintFpResult()
VOID ftrace::PrintFpResult (const PIN_REGISTER * result, ofstream * output)
Prints the result of a floating point instruction to the supplied output file. This function is called for every floating-point arithmetic instruction if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] result Result of the instruction.
[out] output The output file to write to.
Note
All floating-point values are printed as 8 digit hex numbers padded with 0's.
Definition at line 81 of file instrumentation_callbacks.cpp.
Referenced by PrintFpOperations().
PrintMemoryFpOperands()
VOID ftrace::PrintMemoryFpOperands (const OPCODE operation, const PIN_REGISTER * operand1, const FLT32 * operand2, ofstream * output)
Prints the operands of a floating point instruction to the supplied output file. This function is called for every floating-point arithmetic instruction that operates on a register and a memory location if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] operation Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction
[out] output The output file to write to.
Note
All floating-point values are printed as 8 digit hex numbers padded with 0's.
Definition at line 75 of file instrumentation_callbacks.cpp.
Referenced by PrintFpOperations().
PrintRegisterFpOperands()
VOID ftrace::PrintRegisterFpOperands (const OPCODE operation, const PIN_REGISTER * operand1, const PIN_REGISTER * operand2, ofstream * output)
Prints the operands of a floating point instruction to the supplied output file. This function is called for every floating-point arithmetic instruction that operates on two registers if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] operation Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction
[out] output The output file to write to.
Note
All floating-point values are printed as 8 digit hex numbers padded with 0's.
Definition at line 68 of file instrumentation_callbacks.cpp.
Referenced by PrintFpOperations().
ReplaceFpOperations()
VOID ftrace::ReplaceFpOperations (const RTN rtn, FpSelector * fp_selector)
Schedule calls to analysis routines to replace every floating-point operation in the instrumented application with a user-defined implementation. This function is called every time a new routine is encountered, before the instrumented application is run if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] rtn Routine to be instrumented.
[in] fp_selector The floating-point selector to use.
Definition at line 40 of file instrument_routine.cpp.
References EnterFunction(), ExitFunction(), ReplaceMemoryFpInstruction(), and ReplaceRegisterFpInstruction().
ReplaceMemoryFpInstruction()
VOID ftrace::ReplaceMemoryFpInstruction (const OPCODE operation, const REG operand1, const FLT32 * operand2, FpSelector * fp_selector, CONTEXT * ctxt)
Replaces a floating-point operation with a user defined implementation. This function is called for every floating-point arithmetic instruction that operates on a register and a memory location if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] operation Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction
[in,out] fp_selector Floating-point selector which selects the floating-point implementation to use.
[in,out] ctxt Context of the instrumented application, used to store the result of the floating-point operation in the correct register.
Definition at line 43 of file instrumentation_callbacks.cpp.
References ftrace::FpImplementation::FpOperation(), and ftrace::FpSelector::SelectFpImplementation().
Referenced by ReplaceFpOperations().
ReplaceRegisterFpInstruction()
VOID ftrace::ReplaceRegisterFpInstruction (const OPCODE operation, const REG operand1, const REG operand2, FpSelector * fp_selector, CONTEXT * ctxt)
Replaces a floating-point operation with a user defined implementation. This function is called for every floating-point arithmetic instruction that operates on two registers if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in] operation Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction
[in,out] fp_selector Floating-point selector which selects the floating-point implementation to use.
[in,out] ctxt Context of the instrumented application, used to store the result of the floating-point operation in the correct register.
Definition at line 30 of file instrumentation_callbacks.cpp.
References ftrace::FpImplementation::FpOperation(), and ftrace::FpSelector::SelectFpImplementation().
Referenced by ReplaceFpOperations().
StartCallback()
VOID ftrace::StartCallback (FpSelector * fp_selector)
Performs any setup needed by the given floating-point selector. This function is called after Pin initialization is finished but before the instrumented application starts running if the KnobFpSelectorName flag is supplied on the command line.
Parameters
[in,out] fp_selector The floating-point selector to setup.
Definition at line 24 of file instrumentation_callbacks.cpp.
References ftrace::FpSelector::StartCallback().
Variable Documentation
test_nested_function_level_map
const pair<string, FpImplementation *> ftrace::test_nested_function_level_map[] static
Initial value:
=
    {{"helper1", &simple}, {"helper2", &simple}, {"nested_helper", &complex}}
Definition at line 69 of file test_fp_selectors.cpp.
test_nested_function_level_map_size
const int ftrace::test_nested_function_level_map_size static
Initial value:
=
    sizeof(test_nested_function_level_map) /
    sizeof(test_nested_function_level_map[0])
Definition at line 71 of file test_fp_selectors.cpp.
test_simple_function_level_map
const pair<string, FpImplementation *> ftrace::test_simple_function_level_map[] static
Initial value:
=
    {{"helper2", &simple}, {"helper1", &complex}}
Definition at line 64 of file test_fp_selectors.cpp.
test_simple_function_level_map_size
const int ftrace::test_simple_function_level_map_size static
Initial value:
=
    sizeof(test_simple_function_level_map) /
    sizeof(test_simple_function_level_map[0])
Definition at line 66 of file test_fp_selectors.cpp.