ftrace: ftrace::anonymous_namespace{print_fp_bits_manipulated.cpp} Namespace Reference
ftrace::anonymous_namespace{print_fp_bits_manipulated.cpp} Namespace Reference
Functions
VOID CountFpMantissaBits (FLT32 flt)
Variables
UINT64 fp_bits_manipulated = 0
Function Documentation
CountFpMantissaBits()
VOID ftrace::anonymous_namespace{print_fp_bits_manipulated.cpp}::CountFpMantissaBits (FLT32 flt)
Counts the number of bits used in the matissa of the supplied floating-point number and adds the number to a running total.
Parameters
[in] flt The floating-point number.
Note
The number of bits used in the matissa is recorded as 23 minus the least significant set bit in the mantissa.
Definition at line 28 of file print_fp_bits_manipulated.cpp.
References CountFpMantissaBits(), and ftrace::IsFpInstruction().
Referenced by CountFpMantissaBits().
Variable Documentation
fp_bits_manipulated
UINT64 ftrace::anonymous_namespace{print_fp_bits_manipulated.cpp}::fp_bits_manipulated = 0
Keeps track of the number of bits manipulated in every floating-point arithmetic operation in the application.
Definition at line 18 of file print_fp_bits_manipulated.cpp.