NEAT: NEAT::analysis::anonymous_namespace{print_fp_operations.cpp} Namespace Reference
NEAT::analysis::anonymous_namespace{print_fp_operations.cpp} Namespace Reference
Functions
VOID PrintRegisterFpOperands (const OPCODE operation, const PIN_REGISTER *operand1, const PIN_REGISTER *operand2, ofstream *output)
VOID PrintMemoryFpOperands (const OPCODE operation, const PIN_REGISTER *operand1, const FLT32 *operand2, ofstream *output)
VOID PrintFpResult (const PIN_REGISTER *result, ofstream *output)
Function Documentation
PrintFpResult()
VOID NEAT::analysis::anonymous_namespace{print_fp_operations.cpp}::PrintFpResult (const PIN_REGISTER * result, ofstream * output)
Prints the result of a floating point instruction to the supplied output file. This function is called for every floating-point arithmetic instruction if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] result Result of the instruction.
[out] output The output file to write to.
Note
All floating-point values are printed as 8 digit hex numbers padded with 0's.
Definition at line 112 of file print_fp_operations.cpp.
References PrintFpResult().
Referenced by PrintFpResult().
PrintMemoryFpOperands()
VOID NEAT::analysis::anonymous_namespace{print_fp_operations.cpp}::PrintMemoryFpOperands (const OPCODE operation, const PIN_REGISTER * operand1, const FLT32 * operand2, ofstream * output)
Prints the operands of a floating point instruction to the supplied output file. This function is called for every floating-point arithmetic instruction that operates on a register and a memory location if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] operation Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction
[out] output The output file to write to.
Note
All floating-point values are printed as 8 digit hex numbers padded with 0's.
Associative operations print the largest operand first so that the format of the output is identical on different architectures.
Definition at line 84 of file print_fp_operations.cpp.
References PrintMemoryFpOperands().
Referenced by PrintMemoryFpOperands().
PrintRegisterFpOperands()
VOID NEAT::analysis::anonymous_namespace{print_fp_operations.cpp}::PrintRegisterFpOperands (const OPCODE operation, const PIN_REGISTER * operand1, const PIN_REGISTER * operand2, ofstream * output)
Prints the operands of a floating point instruction to the supplied output file. This function is called for every floating-point arithmetic instruction that operates on two registers if the KnobPrintFpOps flag is supplied on the command line.
Parameters
[in] operation Opcode of the floating-point operation.
[in] operand1 First operand of the instruction.
[in] operand2 Second operand of the instruction
[out] output The output file to write to.
Note
All floating-point values are printed as 8 digit hex numbers padded with 0's.
Associative operations print the largest operand first so that the format of the output is identical on different architectures.
Definition at line 48 of file print_fp_operations.cpp.
References PrintRegisterFpOperands().
Referenced by PrintRegisterFpOperands().